# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53e8385088e6f2300f6cbb12ed23c642"
name = "pay-by-gyfter-test"
application_url = "https://dictionary-diamonds-readings-promotes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,unauthenticated_read_product_listings,write_gift_cards,write_products"

[auth]
redirect_urls = [ "https://dictionary-diamonds-readings-promotes.trycloudflare.com/api/auth" ]


[app_proxy]
url = "https://dictionary-diamonds-readings-promotes.trycloudflare.com"
subpath = "wishlist"
prefix = "apps"